#!/bin/zsh
# Remove an org instance: the cloned app, its commands and its instances.conf row.
#
#   usage: remove-instance.sh <slug> [--purge] [--yes]
#
#     --purge   also delete the profile: ~/.claude-<slug> and the Electron
#               user-data dir. That is chat history, settings and login state,
#               and it is NOT recoverable. Without it the profile is kept, so
#               `claude-rebuild <slug>` later picks up exactly where it left off.
#     --yes     skip the confirmation prompt (for scripts).
#
# Works whether or not the slug is still in instances.conf - an orphan clone
# left behind by an earlier edit is removed just the same. Re-running after a
# successful removal is a no-op. The personal /Applications/Claude.app and
# ~/.claude are never touched.
set -euo pipefail
HERE="${0:A:h}"; source "$HERE/lib.sh"
load_instances --optional

PURGE=0; YES=0; SLUG=""
for arg in "$@"; do
  case "$arg" in
    --purge) PURGE=1 ;;
    --yes|-y) YES=1 ;;
    -*) die "unknown option '$arg'   (usage: ${0:t} <slug> [--purge] [--yes])" ;;
    *) [[ -z "$SLUG" ]] || die "one slug at a time, got '$SLUG' and '$arg'"; SLUG="${arg:l}" ;;
  esac
done
[[ -n "$SLUG" ]] || die "usage: ${0:t} <slug> [--purge] [--yes]   (slugs: ${INSTANCE_SLUGS[*]:-none})"

IN_CONF=0
[[ -n "${INSTANCE_LABEL[$SLUG]:-}" ]] && IN_CONF=1

# The label decides the app and data-dir names. Prefer the config; fall back to
# the bundle actually on disk, which is all an orphan leaves us.
APP=""
if (( IN_CONF )); then
  APP="$(app_path "$SLUG")"
  [[ -d "$APP" ]] || APP="$(find_app_by_slug "$SLUG" || true)"
else
  APP="$(find_app_by_slug "$SLUG" || true)"
fi
if [[ -n "$APP" && -d "$APP" ]]; then
  LABEL="$(label_from_app "$APP")"
elif (( IN_CONF )); then
  LABEL="${INSTANCE_LABEL[$SLUG]}"
else
  # App and config row both gone - fall back to the stamp the build left behind.
  LABEL="$(read_stamp_label "$SLUG" 2>/dev/null || true)"
fi

CFG="$(config_dir "$SLUG")"
DATA=""; [[ -n "$LABEL" ]] && DATA="$HOME/Library/Application Support/Claude-$LABEL"
BIN="${CLAUDE_APPS_BIN:-$HOME/.local/bin}"

# Only ever delete commands this tooling generated.
typeset -a CMDS
for n in "claude-$SLUG" "claude-$SLUG-app" "claude-$SLUG-signed"; do
  [[ -f "$BIN/$n" ]] && grep -q "generated by claude-apps" "$BIN/$n" 2>/dev/null && CMDS+=("$BIN/$n")
done

size() { [[ -e "$1" ]] && du -sh "$1" 2>/dev/null | cut -f1 || print -r -- "-"; }

print "==> removing instance '$SLUG'${LABEL:+ (Claude $LABEL)}"
print
print "will delete:"
found=0
[[ -n "$APP"  && -d "$APP"  ]] && { print "  app      $APP  ($(size "$APP"))"; found=1 }
for c in "${CMDS[@]}"; do print "  command  $c"; found=1; done
(( IN_CONF )) && { print "  config   row '$SLUG' in $CONF"; found=1 }
typeset -a SYSPATHS
for pth in ${(f)"$(system_state_paths "$SLUG")"}; do [[ -e "$pth" ]] && SYSPATHS+=("$pth"); done

if (( PURGE )); then
  [[ -d "$CFG" ]]                  && { print "  profile  $CFG  ($(size "$CFG"))"; found=1 }
  [[ -n "$DATA" && -d "$DATA" ]]   && { print "  profile  $DATA  ($(size "$DATA"))"; found=1 }
  for pth in "${SYSPATHS[@]}"; do print "  system   $pth  ($(size "$pth"))"; found=1; done
fi
(( found )) || { print "  (nothing - already removed)"; exit 0 }

if (( ! PURGE )); then
  print
  print "keeping (pass --purge to delete these too):"
  for pth in "${SYSPATHS[@]}"; do print "  ${pth/#$HOME/~}"; done
  [[ -d "$CFG" ]]                && print "  $CFG  ($(size "$CFG"))"
  [[ -n "$DATA" && -d "$DATA" ]] && print "  $DATA  ($(size "$DATA"))"
  [[ -d "$CFG" || ( -n "$DATA" && -d "$DATA" ) ]] || print "  (no profile data on disk)"
fi

if (( ! YES )); then
  print
  (( PURGE )) && print -r -- "--purge deletes chat history and login state. This cannot be undone."
  printf "type the slug '%s' to confirm: " "$SLUG"
  read -r reply
  [[ "$reply" == "$SLUG" ]] || { print "aborted - nothing was changed"; exit 1 }
fi

print
if [[ -n "$APP" && -d "$APP" ]]; then
  print "==> quitting + deleting app"
  pkill -f "${APP:t}/Contents/MacOS/Claude.real" 2>/dev/null || true
  sleep 1
  lsregister -u "$APP" 2>/dev/null || true
  safe_rm "$APP"
fi

for c in "${CMDS[@]}"; do print "==> rm ${c:t}"; rm -f "$c"; done

if (( IN_CONF )); then
  print "==> dropping '$SLUG' from ${CONF:t}"
  conf_remove_slug "$SLUG"
fi

if (( PURGE )); then
  [[ -d "$CFG" ]]                && { print "==> rm $CFG";  safe_rm "$CFG" }
  [[ -n "$DATA" && -d "$DATA" ]] && { print "==> rm $DATA"; safe_rm "$DATA" }
  if (( ${#SYSPATHS} )); then
    print "==> per-bundle-id state (preferences, caches, cookies)"
    # cfprefsd caches preferences in memory and will rewrite the plist on exit,
    # so ask it to forget the domain before deleting the file.
    defaults delete "$(bundle_id "$SLUG")" 2>/dev/null || true
    for pth in "${SYSPATHS[@]}"; do print "    rm ${pth/#$HOME/~}"; safe_rm "$pth"; done
  fi
fi

# Keeping the profile means a later --purge still has to find the data dir.
(( PURGE )) || { [[ -n "$LABEL" ]] && write_stamp "$SLUG" "$LABEL" }

killall Dock 2>/dev/null || true
print
print "done."
if (( ! PURGE )) && [[ -d "$CFG" || ( -n "$DATA" && -d "$DATA" ) ]]; then
  print "profile kept. 'claude-rebuild $SLUG' (after re-adding the row) reuses it;"
  print "'${0:t} $SLUG --purge' deletes it."
fi
