#!/bin/zsh
# Regenerate the ~/.local/bin commands from instances.conf.
# Run after adding, renaming or removing an instance.
# Only touches files carrying this tooling's marker, so hand-written scripts
# in ~/.local/bin are left alone.
set -euo pipefail
HERE="${0:A:h}"; source "$HERE/lib.sh"
load_instances

BIN="${CLAUDE_APPS_BIN:-$HOME/.local/bin}"
MARK="# generated by claude-apps from instances.conf - edits will be overwritten"
mkdir -p "$BIN"

gen() {  # name, body
  print -r -- "#!/bin/zsh"  > "$BIN/$1"
  print -r -- "$MARK"      >> "$BIN/$1"
  print -r -- "$2"         >> "$BIN/$1"
  chmod +x "$BIN/$1"
  print "  + $1"
}

print "==> per-instance commands"
typeset -A keep
for slug in "${INSTANCE_SLUGS[@]}"; do
  # Backfills the slug -> label stamp for instances built before it existed;
  # claude-remove needs it to locate the data dir once the app is gone.
  write_stamp "$slug" "${INSTANCE_LABEL[$slug]}"
  gen "claude-$slug"     "CLAUDE_CONFIG_DIR=\"$(config_dir "$slug")\" exec claude \"\$@\""
  gen "claude-$slug-app" "exec open -a \"Claude ${INSTANCE_LABEL[$slug]}\" \"\$@\""
  keep[claude-$slug]=1; keep[claude-$slug-app]=1
done

print "==> shared commands"
for pair in \
  "claude-install:install.sh" \
  "claude-rebuild:rebuild-claude-org.sh" \
  "claude-icon:set-claude-icon.sh" \
  "claude-default:set-default-handler.sh" \
  "claude-update-all:update-all.sh" \
  "claude-instances:list-instances.sh" \
  "claude-remove:remove-instance.sh" \
  "claude-sync:sync-commands.sh"
do
  name="${pair%%:*}"; script="${pair#*:}"
  gen "$name" "exec \"$HERE/$script\" \"\$@\""
  keep[$name]=1
done

print "==> pruning commands for removed instances"
pruned=0
for f in "$BIN"/claude-*(N); do
  [[ -f "$f" ]] || continue
  n="${f:t}"
  [[ -n "${keep[$n]:-}" ]] && continue
  grep -q "generated by claude-apps" "$f" 2>/dev/null || continue   # never ours -> leave it
  rm -f "$f"; print "  - $n"; pruned=$((pruned+1))
done
(( pruned )) || print "  (nothing to prune)"

# A command that is not on PATH is no use to anyone.
case ":$PATH:" in
  *":$BIN:"*) ;;
  *) print
     print "WARNING: $BIN is not on your PATH. Add it, e.g.:"
     print "    echo 'export PATH=\"$BIN:\$PATH\"' >> ~/.zshrc"
     print "  or point this tooling elsewhere with CLAUDE_APPS_BIN." ;;
esac

print
print "done. commands in $BIN:"
ls -1 "$BIN" | grep '^claude-' | sed 's/^/  /'
